import type { NextConfig } from 'next';
import * as fs from 'fs';
import * as path from 'path';

const repository = process.env.GITHUB_REPOSITORY;
const owner = process.env.GITHUB_REPOSITORY_OWNER;
const isGitHubActions = process.env.GITHUB_ACTIONS === 'true';
const isProduction = process.env.NODE_ENV === 'production';
const explicitBasePath = process.env.NEXT_PUBLIC_BASE_PATH;

const fallbackProjectBasePath = '/MV-Fashion';

const repoName = repository?.split('/')[1] ?? '';
const isUserOrOrgPage = !!owner && repoName.toLowerCase() === `${owner.toLowerCase()}.github.io`;
const basePathFromRepository = isGitHubActions && repoName && !isUserOrOrgPage ? `/${repoName}` : '';
const basePath = explicitBasePath
  || basePathFromRepository
  || (isProduction ? fallbackProjectBasePath : '');
const siteUrl = owner ? `https://${owner}.github.io${basePath}` : 'https://hunorlaczko.github.io/MV-Fashion';

// Write build-time constants for the app to use
const generatedPath = path.join(__dirname, 'src/lib/basePath.generated.ts');
fs.writeFileSync(generatedPath,
  `// AUTO-GENERATED by next.config.ts — do not edit manually\n` +
  `export const BASE_PATH = ${JSON.stringify(basePath)};\n` +
  `export const SITE_URL = ${JSON.stringify(siteUrl)};\n`
);

const nextConfig: NextConfig = {
  output: 'export',
  trailingSlash: true,
  basePath,
  assetPrefix: basePath || undefined,
  experimental: {
    optimizePackageImports: ['lucide-react'],
  },
  images: {
    unoptimized: true,
  },
};

export default nextConfig;
